source 'https://rubygems.org'
gem 'allure-cucumber', '~> 0.6.1'
gem 'allure-ruby-commons'
gem 'cucumber'
gem 'minitest'
gem 'page-object'
gem 'rake'
gem 'rspec', '~> 3.4'
gem 'rubocop', group: 'development', require: false
gem 'selenium-webdriver'
gem 'test-unit'