version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:2.7  # Adjust to your Ruby version
      - image: circleci/openjdk:11  # For Allure, requires Java
        environment:
          BROWSERSTACK_USERNAME: "<your-browserstack-username>"
          BROWSERSTACK_ACCESS_KEY: "<your-browserstack-access-key>"
          JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"  # Set JAVA_HOME
          PATH: "/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"

parameters:
  tags:
    type: string
    default: "@test"
  env:
    type: string
    default: "prod"
  platform:
    type: string
    default: "browserstack"

jobs:
  test:
    executor: ruby-executor
    parameters:
      tags:
        type: string
        default: "<< pipeline.parameters.tags >>"
      env:
        type: string
        default: "<< pipeline.parameters.env >>"
      platform:
        type: string
        default: "<< pipeline.parameters.platform >>"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler -v 2.4.22
            bundle install
      - run:
          name: Install Node.js and npm
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
      - run:
          name: Install Allure Commandline
          command: |
            sudo npm install -g allure-commandline
      - run:
          name: Execute Tests
          command: |
            bundle exec rake run TAGS='<< parameters.tags >>' ENV='<< parameters.env >>' PLATFORM='<< parameters.platform >>'
      - run:
          name: Generate Allure Report
          command: |
            echo BRANCH=development >> allure-results/environment.properties
            echo COMMIT=$CI_PULL_REQUEST/commits/$CIRCLE_SHA1 >> allure-results/environment.properties
            allure generate --clean
          when: always
      - store_artifacts:
          path: /home/circleci/project/allure-report
          destination: allure-report
      - store_test_results:
          path: allure-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          tags: "<< pipeline.parameters.tags >>"
          env: "<< pipeline.parameters.env >>"
          platform: "<< pipeline.parameters.platform >>"
