version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:2.7  # Adjust to your Ruby version
      - image: circleci/openjdk:11  # For Allure, requires Java
        environment:
          BROWSERSTACK_USERNAME: "<your-browserstack-username>"
          BROWSERSTACK_ACCESS_KEY: "<your-browserstack-access-key>"

parameters:
  tags:
    type: string
    default: "@test"
  env:
    type: string
    default: "prod"
  platform:
    type: string
    default: "browserstack"

jobs:
  test:
    executor: ruby-executor
    parameters:
      tags:
        type: string
        default: "<< pipeline.parameters.tags >>"
      env:
        type: string
        default: "<< pipeline.parameters.env >>"
      platform:
        type: string
        default: "<< pipeline.parameters.platform >>"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler -v 2.4.22
            bundle install
      - run:
          name: Execute Tests
          command: |
            bundle exec rake run TAGS='<< parameters.tags >>' ENV='<< parameters.env >>' PLATFORM='<< parameters.platform >>'

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          tags: "<< pipeline.parameters.tags >>"
          env: "<< pipeline.parameters.env >>"
          platform: "<< pipeline.parameters.platform >>"
