version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:2.7  # Adjust to your Ruby version
      - image: circleci/openjdk:11  # For Allure, requires Java

parameters:
  tags:
    type: string
    default: "@test"
  env:
    type: string
    default: "prod"
  platform:
    type: string
    default: "browserstack"

jobs:
  test:
    executor: ruby-executor
    parameters:
      tags:
        type: string
        default: "<< pipeline.parameters.tags >>"
      env:
        type: string
        default: "<< pipeline.parameters.env >>"
      platform:
        type: string
        default: "<< pipeline.parameters.platform >>"
    steps:
      - checkout
      - restore_cache:  # Restore the cache for the gems
          keys:
            - bundler-v1-{{ checksum "Gemfile.lock" }}  # Uses the Gemfile.lock checksum to restore the cache
            - bundler-v1-  # Fallback in case there's no exact match
      - run:
          name: Install Dependencies
          command: |
            gem install bundler -v 2.4.22
            bundle install --path vendor/bundle
      - save_cache:  # Save the gems cache
          paths:
            - vendor/bundle
          key: bundler-v1-{{ checksum "Gemfile.lock" }}
      - restore_cache:  # Restore node.js and npm cache
          keys:
            - nodejs-npm-cache-v1
      - run:
          name: Install Node.js and npm
          command: |
            if ! command -v node > /dev/null || ! command -v npm > /dev/null; then
              sudo apt-get update
              sudo apt-get install -y nodejs npm
            fi
      - save_cache:  # Save node.js and npm cache
          paths:
            - /usr/bin/node
            - /usr/bin/npm
          key: nodejs-npm-cache-v1
      - restore_cache:  # Restore the Java installation cache
          keys:
            - java-cache-v1
      - run:
          name: Ensure Java is Installed
          command: |
            if ! command -v java > /dev/null; then
              sudo apt-get update
              sudo apt-get install -y openjdk-11-jdk  # Install Java if not already present
            fi
            export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
            export PATH="$JAVA_HOME/bin:$PATH"
            echo 'export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"' >> ~/.bashrc
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
            java -version
      - run:
          name: Install Allure Commandline
          command: |
            sudo npm install -g allure-commandline
            export PATH=$PATH:$(npm bin -g)
      - run:
          name: Execute Tests
          command: |
            bundle exec rake run TAGS='<< parameters.tags >>' ENV='<< parameters.env >>' PLATFORM='<< parameters.platform >>'
      - run:
          name: Generate Allure Report
          command: |
            export PATH=$PATH:$(npm bin -g)  # Ensure the path includes npm binaries
            mkdir -p allure-results
            echo "BRANCH=$CIRCLE_BRANCH" >> allure-results/environment.properties
            echo "COMMIT=$CIRCLE_SHA1" >> allure-results/environment.properties
            allure generate allure-results --clean -o allure-report
          when: always
      - store_artifacts:
          path: /home/circleci/project/allure-report
          destination: allure-report
      - store_test_results:
          path: allure-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          tags: "<< pipeline.parameters.tags >>"
          env: "<< pipeline.parameters.env >>"
          platform: "<< pipeline.parameters.platform >>"
