userName: alperctest_Ug4qG2
accessKey: eyEAqzbsNpYEX2sHhUGH
platforms:
  - os: OS X
    osVersion: Sonoma
    browserName: Chrome
    browserVersion: latest
  - os: Windows
    osVersion: 11
    browserName: Firefox
    browserVersion: latest
  - os: Windows
    osVersion: 11
    browserName: Chrome
    browserVersion: latest
browserstackLocal: true
buildName: bstack-demo
projectName: BrowserStack Sample
debug: true
networkLogs: true
consoleLogs: info