userName: alper_RJL3vD
accessKey: xqqySMEEF7pNMsyQyxc9
platforms:
  - os: OS X
    osVersion: Sonoma
    browserName: Chrome
    browserVersion: latest
    debug: true
    networkLogs: true
    consoleLogs: info
  - os: Windows
    osVersion: 11
    browserName: Firefox
    browserVersion: latest
    debug: true
    networkLogs: true
    consoleLogs: info
  - os: Windows
    osVersion: 11
    browserName: Chrome
    browserVersion: latest
    debug: true
    networkLogs: true
    consoleLogs: info
buildName: bstack-demo
projectName: BrowserStack Sample
local: false

