name: UI Test Automation

on:
  workflow_dispatch:
    inputs:
      TAGS:
        description: 'Cucumber tags to run'
        required: false
        default: '@test'
      ENV:
        description: 'Test environment'
        required: false
        default: 'prod'
      PLATFORM:
        description: 'Execution platform'
        required: false
        default: 'browserstack'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run UI Tests
        run: |
          bundle exec rake run TAGS='${{ github.event.inputs.TAGS }}' ENV='${{ github.event.inputs.ENV }}' PLATFORM='${{ github.event.inputs.PLATFORM }}'

      - name: Generate Allure Report
        run: |
          allure generate --clean
          # Archive the Allure results directory
          tar -czf allure-results.tar.gz allure-results

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results.tar.gz
