---
name: Ruby
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          gem install cucumber
          gem install page-object
          gem install allure-cucumber
          bundle install
      - name: Run tests
        run: rake run TAGS="@smoke" PLATFORM="browserstack"
      - name: Allure report
        uses: afiore/action-allure-report@v0.1.0
        with:
          results-dir: null
          report-dir: null
