---
name: TestAutomation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write # We generate static HTML, JS, CSS so we need write access to the repo
  pages: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          gem install cucumber
          gem install page-object
          gem install allure-cucumber
          bundle install
      - name: Run tests
        run: rake run TAGS="@test" PLATFORM="browserstack"
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-report/data/test-cases
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
